services:
  renderer:
    image: rlespinasse/drawio-desktop-headless:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
    entrypoint:
      - sh
      - scripts/render.sh
    command:
      - architecture/raw
      - architecture/rendered
      - png
