services:
  renderer:
    image: rlespinasse/drawio-desktop-headless:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
    entrypoint:
      - /bin/sh
      - -lc
    command: "sh scripts/render.sh architecture/raw architecture/rendered png"
